### ISSUE TITLE
Tests Clean Up

### ISSUE THREAD

**Issue by saspeed** [studentenportal/web#180] opened 2016-03-14 12:05 UTC
Running the tests on my local machine, the current report states 

> 9 failed, 111 passed, 66 skipped 

which is a 66% pass rate. This issue shall track the refactoring of our test suite to get back to a level of at least 90%.

**Comment by The-Compiler** [comment] 2019-12-28 16:51
I can't reproduce:

```
100 passed, 251 warnings in 132.97 seconds 
```

Looking at the warnings, they are all because of deprecated Django APIs, so I'm guessing they'll get fixed as part of #215 and #225 

I'm guessing the test failures were fixed as part of #193, so I'm closing this.

**Closed by The-Compiler** 2019-12-28 16:51 UTC
Labels: Size: M, Type: Refactoring
